- name: Create VPC
  ec2_vpc:
    aws_access_key: {{ aws_access_key }}
    aws_secret_key: {{ aws_secret_key }}
    cidr_block: 10.0.0.0/16
      resource_tags: { "Name" : {{ vpc_name }} }
      subnets:
        - cidr: {{ subnet_cidr }}
          #az: us-west-2c
          resource_tags: { "Name" : {{ subnet_name }} }
        #- cidr: 10.0.1.0/24
          #az: us-west-2b
          #resource_tags: { "Name" : "Management subnet" }
        #- cidr: 10.0.2.0/24
          #az: us-west-2a
          #resource_tags: { "Name" : "Dev", "Tier" : "DB" }
      with_items: "{{ vpc_subnets }}"
      internet_gateway: True
      route_tables:
        - subnets:
            - 172.22.2.0/24
            - 172.22.3.0/24
          routes:
            - dest: 0.0.0.0/0
              gw: igw
        - subnets:
            - 172.22.1.0/24
          routes:
            - dest: 0.0.0.0/0
              gw: igw
      region: us-west-2
    register: vpc
