- name: Check we are using the right AWS keys
  debug: msg="Access key is {{ amazon_access_key }}, secret key is {{ amazon_secret_key }}"

- name: Create VPC
  ec2_vpc:
    aws_access_key: "{{ amazon_access_key }}"
    aws_secret_key: "{{ amazon_secret_key }}"
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: { "Name" : "{{ vpc_name }}" }
    subnets: "{{ subnet_list }}"
    internet_gateway: True
    dns_hostnames: yes
    dns_support: yes
    region: "{{ amazon_region }}"
  register: vpc

- name: Print out VPC object
  debug: var="{{ vpc }}"
  when: debug_playbook is defined

- name: See if we have created a new VPC or not
  debug: msg="New VPC created with id {{ vpc.vpc_id }}"
  when: vpc.changed
